# GitHub Actions template (starting point)
# - Uses canonical pnpm scripts for each suite
# - Uploads suite artifacts even on failure
#
# - Optional: run `node .ai/skills/features/ci/scripts/cictl.js init` to create `ci/config.json` metadata
#
# NOTE: Adjust Node version, secrets, and which jobs are PR-gated for your repo.

name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-newman:
    name: API (Newman)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run API tests
        run: pnpm test:api
        env:
          BASE_URL: ${{ secrets.API_BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Upload API artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-api-newman
          path: artifacts/newman

  web-playwright:
    name: Web (Playwright)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright E2E
        run: pnpm test:e2e:playwright
        env:
          BASE_URL: ${{ secrets.WEB_BASE_URL }}

      - name: Upload Playwright artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-web-playwright
          path: artifacts/playwright

  perf-k6-smoke:
    name: Perf (k6 smoke)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # Recommended: keep k6 smoke in PR; heavier perf suites should be scheduled.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup k6 (Docker)
        run: docker pull grafana/k6:latest

      - name: Run k6 smoke
        run: |
          mkdir -p artifacts/k6
          docker run --rm \
            -e BASE_URL="${BASE_URL}" \
            -e API_TOKEN="${API_TOKEN}" \
            -v "${PWD}:/work" -w /work \
            grafana/k6:latest \
            run tests/perf/k6/scripts/smoke.js --summary-export artifacts/k6/summary.json
        env:
          BASE_URL: ${{ secrets.API_BASE_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}

      - name: Upload k6 artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-perf-k6
          path: artifacts/k6

  # Optional: Cypress job (enable only if you gate on Cypress)
  # web-cypress:
  #   name: Web (Cypress)
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "pnpm"
  #     - run: corepack enable
  #     - run: pnpm install --frozen-lockfile
  #     - run: pnpm test:e2e:cypress
  #       env:
  #         WEB_BASE_URL: ${{ secrets.WEB_BASE_URL }}
  #     - if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: artifacts-web-cypress
  #         path: artifacts/cypress
