#!/usr/bin/env node
/**
 * cictl.js - CI Configuration Management
 *
 * Manages CI/CD configuration and workflow generation.
 *
 * Commands:
 *   init              Initialize CI configuration
 *   enable-feature    Enable a CI feature
 *   disable-feature   Disable a CI feature
 *   list-features     List all features and their status
 *   generate          Generate workflow files from configuration
 *   verify            Verify CI configuration
 *   status            Show current CI status
 *   help              Show this help message
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ─────────────────────────────────────────────────────────────────────────────
// Configuration
// ─────────────────────────────────────────────────────────────────────────────

const CI_DIR = 'ci';
const CI_CONFIG_FILE = 'ci/config.json';
const CI_WORKDOCS_DIR = 'ci/workdocs';
const GITHUB_WORKFLOWS_DIR = '.github/workflows';
const GITLAB_CI_DIR = '.gitlab-ci';

const AVAILABLE_FEATURES = ['lint', 'test', 'build', 'security', 'release', 'deploy'];
const SUPPORTED_PLATFORMS = ['github-actions', 'gitlab-ci'];

// ─────────────────────────────────────────────────────────────────────────────
// Utilities
// ─────────────────────────────────────────────────────────────────────────────

function parseArgs(args) {
  const result = { _: [], flags: {} };
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith('--')) {
      const key = arg.slice(2);
      const nextArg = args[i + 1];
      if (nextArg && !nextArg.startsWith('--')) {
        result.flags[key] = nextArg;
        i++;
      } else {
        result.flags[key] = true;
      }
    } else {
      result._.push(arg);
    }
  }
  return result;
}

function resolveRepoRoot(flagValue) {
  if (flagValue) return resolve(flagValue);
  return resolve(__dirname, '..', '..');
}

function isoNow() {
  return new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
}

function ensureDir(dirPath) {
  if (!existsSync(dirPath)) {
    mkdirSync(dirPath, { recursive: true });
    return true;
  }
  return false;
}

function loadJson(filePath) {
  if (!existsSync(filePath)) return null;
  try {
    return JSON.parse(readFileSync(filePath, 'utf8'));
  } catch (e) {
    console.error(`Error reading ${filePath}: ${e.message}`);
    return null;
  }
}

function saveJson(filePath, data) {
  ensureDir(dirname(filePath));
  writeFileSync(filePath, JSON.stringify(data, null, 2));
}

function loadConfig(repoRoot) {
  return loadJson(join(repoRoot, CI_CONFIG_FILE));
}

function saveConfig(repoRoot, config) {
  config.updatedAt = isoNow();
  saveJson(join(repoRoot, CI_CONFIG_FILE), config);
}

// ─────────────────────────────────────────────────────────────────────────────
// Workflow Templates
// ─────────────────────────────────────────────────────────────────────────────

function generateGitHubWorkflow(config) {
  const features = config.features || [];
  
  let jobs = '';
  
  if (features.includes('lint')) {
    jobs += `
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
`;
  }
  
  if (features.includes('test')) {
    jobs += `
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test
`;
  }
  
  if (features.includes('build')) {
    jobs += `
  build:
    runs-on: ubuntu-latest
    ${features.includes('lint') || features.includes('test') ? `needs: [${[features.includes('lint') ? 'lint' : '', features.includes('test') ? 'test' : ''].filter(Boolean).join(', ')}]` : ''}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
`;
  }
  
  if (features.includes('security')) {
    jobs += `
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run security audit
        run: npm audit --audit-level=high
`;
  }

  return `# CI Workflow
# Generated by cictl.js - ${isoNow()}
# Modify ci/config.json and run 'node .ai/scripts/cictl.js generate' to update

name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:${jobs || `
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No features enabled. Run 'node .ai/scripts/cictl.js enable-feature <feature>'"
`}
`;
}

function generateGitLabCI(config) {
  const features = config.features || [];
  
  let stages = [];
  let jobs = '';
  
  if (features.includes('lint')) {
    stages.push('lint');
    jobs += `
lint:
  stage: lint
  image: node:20
  script:
    - npm ci
    - npm run lint
`;
  }
  
  if (features.includes('test')) {
    stages.push('test');
    jobs += `
test:
  stage: test
  image: node:20
  script:
    - npm ci
    - npm test
`;
  }
  
  if (features.includes('build')) {
    stages.push('build');
    jobs += `
build:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build
`;
  }

  return `# GitLab CI Configuration
# Generated by cictl.js - ${isoNow()}

stages:
${stages.length > 0 ? stages.map(s => `  - ${s}`).join('\n') : '  - placeholder'}
${jobs || `
placeholder:
  stage: placeholder
  script:
    - echo "No features enabled"
`}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Commands
// ─────────────────────────────────────────────────────────────────────────────

function cmdInit(repoRoot, flags) {
  const { platform = 'github-actions' } = flags;

  if (!SUPPORTED_PLATFORMS.includes(platform)) {
    console.error(`Error: Unsupported platform "${platform}".`);
    console.error(`Supported: ${SUPPORTED_PLATFORMS.join(', ')}`);
    return 1;
  }

  console.log(`Initializing CI configuration at ${repoRoot}...`);
  let created = false;

  // Create CI directory
  const ciDir = join(repoRoot, CI_DIR);
  if (ensureDir(ciDir)) {
    console.log(`  Created: ${CI_DIR}/`);
    created = true;
  }

  // Create workdocs directory
  const workdocsDir = join(repoRoot, CI_WORKDOCS_DIR);
  if (ensureDir(workdocsDir)) {
    console.log(`  Created: ${CI_WORKDOCS_DIR}/`);
    created = true;
  }

  // Create config file
  const configPath = join(repoRoot, CI_CONFIG_FILE);
  if (!existsSync(configPath)) {
    const initialConfig = {
      version: 1,
      updatedAt: isoNow(),
      platform,
      features: [],
      generated: false
    };
    saveJson(configPath, initialConfig);
    console.log(`  Created: ${CI_CONFIG_FILE}`);
    created = true;
  } else {
    // Update platform if different
    const config = loadConfig(repoRoot);
    if (config && config.platform !== platform) {
      config.platform = platform;
      saveConfig(repoRoot, config);
      console.log(`  Updated platform to: ${platform}`);
    }
  }

  // Create AGENTS.md
  const agentsPath = join(repoRoot, CI_DIR, 'AGENTS.md');
  if (!existsSync(agentsPath)) {
    const agentsContent = `# CI Configuration - AI Guidance

## Conclusions (read first)

- CI configuration is managed via \`cictl.js\`.
- Do NOT edit workflow files directly; use \`cictl generate\` to regenerate.
- Features are enabled/disabled in \`ci/config.json\`.

## Workflow

1. Enable features: \`node .ai/scripts/cictl.js enable-feature <feature>\`
2. Generate workflows: \`node .ai/scripts/cictl.js generate\`
3. Commit the generated files

## Available Features

- \`lint\` - Code linting
- \`test\` - Test execution
- \`build\` - Build step
- \`security\` - Security scanning
- \`release\` - Release automation
- \`deploy\` - Deployment triggers

## Current Platform

Check \`ci/config.json\` for the configured CI platform.
`;
    writeFileSync(agentsPath, agentsContent);
    console.log(`  Created: ${CI_DIR}/AGENTS.md`);
    created = true;
  }

  // Create workdocs README
  const workdocsReadme = join(workdocsDir, 'README.md');
  if (!existsSync(workdocsReadme)) {
    writeFileSync(workdocsReadme, '# CI Workdocs\n\nUse this directory for CI planning and notes.\n');
    console.log(`  Created: ${CI_WORKDOCS_DIR}/README.md`);
    created = true;
  }

  if (!created) {
    console.log('  CI configuration already initialized (no changes).');
  }

  console.log('Done.');
  console.log(`\nNext: Enable features with 'node .ai/scripts/cictl.js enable-feature <feature>'`);
  return 0;
}

function cmdEnableFeature(repoRoot, flags) {
  const feature = flags._remainder?.[0] || flags.feature;

  if (!feature) {
    console.error('Error: Feature name required.');
    console.error(`Available: ${AVAILABLE_FEATURES.join(', ')}`);
    return 1;
  }

  if (!AVAILABLE_FEATURES.includes(feature)) {
    console.error(`Error: Unknown feature "${feature}".`);
    console.error(`Available: ${AVAILABLE_FEATURES.join(', ')}`);
    return 1;
  }

  const config = loadConfig(repoRoot);
  if (!config) {
    console.error('Error: CI not initialized. Run `cictl init` first.');
    return 1;
  }

  if (!config.features) config.features = [];
  
  if (config.features.includes(feature)) {
    console.log(`Feature "${feature}" is already enabled.`);
    return 0;
  }

  config.features.push(feature);
  config.generated = false; // Mark as needing regeneration
  saveConfig(repoRoot, config);

  console.log(`Enabled feature: ${feature}`);
  console.log(`\nRun 'node .ai/scripts/cictl.js generate' to update workflow files.`);
  return 0;
}

function cmdDisableFeature(repoRoot, flags) {
  const feature = flags._remainder?.[0] || flags.feature;

  if (!feature) {
    console.error('Error: Feature name required.');
    return 1;
  }

  const config = loadConfig(repoRoot);
  if (!config) {
    console.error('Error: CI not initialized.');
    return 1;
  }

  const idx = config.features?.indexOf(feature);
  if (idx === -1 || idx === undefined) {
    console.log(`Feature "${feature}" is not enabled.`);
    return 0;
  }

  config.features.splice(idx, 1);
  config.generated = false;
  saveConfig(repoRoot, config);

  console.log(`Disabled feature: ${feature}`);
  console.log(`\nRun 'node .ai/scripts/cictl.js generate' to update workflow files.`);
  return 0;
}

function cmdListFeatures(repoRoot) {
  const config = loadConfig(repoRoot);
  const enabled = config?.features || [];

  console.log('CI Features:\n');
  for (const f of AVAILABLE_FEATURES) {
    const status = enabled.includes(f) ? '[enabled]' : '[disabled]';
    console.log(`  ${f.padEnd(12)} ${status}`);
  }
  return 0;
}

function cmdGenerate(repoRoot) {
  const config = loadConfig(repoRoot);
  if (!config) {
    console.error('Error: CI not initialized. Run `cictl init` first.');
    return 1;
  }

  const platform = config.platform || 'github-actions';
  console.log(`Generating CI workflows for ${platform}...`);

  if (platform === 'github-actions') {
    const workflowsDir = join(repoRoot, GITHUB_WORKFLOWS_DIR);
    ensureDir(workflowsDir);
    
    const workflow = generateGitHubWorkflow(config);
    const workflowPath = join(workflowsDir, 'ci.yaml');
    writeFileSync(workflowPath, workflow);
    console.log(`  Generated: ${GITHUB_WORKFLOWS_DIR}/ci.yaml`);
  } else if (platform === 'gitlab-ci') {
    const gitlabDir = join(repoRoot, GITLAB_CI_DIR);
    ensureDir(gitlabDir);
    
    const ciConfig = generateGitLabCI(config);
    const ciPath = join(gitlabDir, '.gitlab-ci.yml');
    writeFileSync(ciPath, ciConfig);
    console.log(`  Generated: ${GITLAB_CI_DIR}/.gitlab-ci.yml`);
  }

  config.generated = true;
  config.lastGenerated = isoNow();
  saveConfig(repoRoot, config);

  console.log('Done.');
  return 0;
}

function cmdVerify(repoRoot) {
  const config = loadConfig(repoRoot);
  if (!config) {
    console.error('Error: CI configuration not found.');
    return 1;
  }

  console.log('Verifying CI configuration...');
  let errors = 0;

  // Check platform
  if (!config.platform) {
    console.error('  ERROR: No platform configured');
    errors++;
  } else if (!SUPPORTED_PLATFORMS.includes(config.platform)) {
    console.error(`  ERROR: Unsupported platform: ${config.platform}`);
    errors++;
  } else {
    console.log(`  OK: Platform = ${config.platform}`);
  }

  // Check features
  const enabled = config.features || [];
  console.log(`  OK: ${enabled.length} feature(s) enabled`);

  // Check if generated
  if (!config.generated && enabled.length > 0) {
    console.warn('  Warning: Configuration changed but workflows not regenerated');
    console.warn('  Run: node .ai/scripts/cictl.js generate');
  }

  // Check workflow files exist
  if (config.platform === 'github-actions') {
    const workflowPath = join(repoRoot, GITHUB_WORKFLOWS_DIR, 'ci.yaml');
    if (existsSync(workflowPath)) {
      console.log(`  OK: ${GITHUB_WORKFLOWS_DIR}/ci.yaml exists`);
    } else if (enabled.length > 0) {
      console.warn(`  Warning: ${GITHUB_WORKFLOWS_DIR}/ci.yaml not found`);
    }
  }

  if (errors > 0) {
    console.error(`\nVerification FAILED: ${errors} error(s).`);
    return 1;
  }

  console.log('\nVerification passed.');
  return 0;
}

function cmdStatus(repoRoot) {
  const config = loadConfig(repoRoot);
  if (!config) {
    console.log('CI not configured.');
    console.log('Run: node .ai/scripts/cictl.js init --platform github-actions');
    return 0;
  }

  console.log('CI Status:\n');
  console.log(`  Platform: ${config.platform || 'not set'}`);
  console.log(`  Features: ${config.features?.join(', ') || 'none'}`);
  console.log(`  Generated: ${config.generated ? 'yes' : 'no'}`);
  if (config.lastGenerated) {
    console.log(`  Last generated: ${config.lastGenerated}`);
  }
  return 0;
}

function cmdHelp() {
  console.log(`
cictl.js - CI Configuration Management

Usage: node .ai/scripts/cictl.js <command> [options]

Commands:
  init                Initialize CI configuration
    --platform <p>    CI platform: github-actions, gitlab-ci (default: github-actions)
    
  enable-feature <f>  Enable a CI feature
  disable-feature <f> Disable a CI feature
  list-features       List all features and their status
  
  generate            Generate workflow files from configuration
  verify              Verify CI configuration
  status              Show current CI status
  
  help                Show this help message

Global Options:
  --repo-root <path>  Repository root (default: auto-detect)

Available Features:
  lint, test, build, security, release, deploy

Examples:
  node .ai/scripts/cictl.js init --platform github-actions
  node .ai/scripts/cictl.js enable-feature lint
  node .ai/scripts/cictl.js enable-feature test
  node .ai/scripts/cictl.js generate
`);
  return 0;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const parsed = parseArgs(args);
  const command = parsed._[0] || 'help';
  const repoRoot = resolveRepoRoot(parsed.flags['repo-root']);
  
  // Handle feature argument for enable/disable
  if ((command === 'enable-feature' || command === 'disable-feature') && parsed._[1]) {
    parsed.flags._remainder = [parsed._[1]];
  }

  switch (command) {
    case 'init':
      return cmdInit(repoRoot, parsed.flags);
    case 'enable-feature':
      return cmdEnableFeature(repoRoot, parsed.flags);
    case 'disable-feature':
      return cmdDisableFeature(repoRoot, parsed.flags);
    case 'list-features':
      return cmdListFeatures(repoRoot);
    case 'generate':
      return cmdGenerate(repoRoot);
    case 'verify':
      return cmdVerify(repoRoot);
    case 'status':
      return cmdStatus(repoRoot);
    case 'help':
    case '--help':
    case '-h':
      return cmdHelp();
    default:
      console.error(`Unknown command: ${command}`);
      return cmdHelp() || 1;
  }
}

process.exit(main());

